### ISSUE TITLE
Hash::Agnostic and Array::Agnostic can't both be used

### ISSUE THREAD

**Issue by wayland** [lizmat/Array-Agnostic#3]
Example code causing fail (in file faildemo):
```
#!/usr/bin/raku

use     Hash::Agnostic;
use     Array::Agnostic;
```

Error caused:
```
$ raku faildemo
===SORRY!=== Error while compiling /home/wayland/src/TOP/src/Raku/faildemo
Merging GLOBAL symbols failed: duplicate definition of symbol NoImplementation
at /home/wayland/src/TOP/src/Raku/faildemo:4
```

Suggested solution: A common ancestor that defines NoImplementation, amongst other things.

**Comment by lizmat** [comment]
Thanks for your report!

Although a common ancestor would be nice, it also feels like having another unnecessary dependency.  And I think unnecessary dependencies are bad  :-)

Fixed this by renaming the exception class in both `Array::Agnostic` and `Hash::Agnostic`.  Now as version .12 in the ecosystem!

**Comment by wayland** [comment]
Good call!  Thanks very much :) .  This will be useful for my Table class :-) .
